name: Daily/Pull Request Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '00 10 * * 1-5'

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install system dependencies
        run: sudo apt-get install -y

      - name: Install NPM dependencies
        run: npm ci

      - name: Create cypress.env.json file
        run: |
          echo '{
            "user": {
              "CYPRESS_USER": "${{ secrets.CYPRESS_USER }}",
              "CYPRESS_PASSWORD": "${{ secrets.CYPRESS_PASSWORD }}",
              "CYPRESS_INVALID_PASSWORD": "${{ secrets.CYPRESS_INVALID_PASSWORD }}"
            }
          }' > cypress.env.json
          
      - name: Run Cypress tests
        run: npx cypress run --headless --browser chrome --config defaultCommandTimeout=60000
